version: '3.5'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"

  service:
    image: com.github.gregwhitaker/dbmigrator
    environment:
      - DB_JDBC_URL=jdbc:mysql://host.docker.internal:5432/postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=changeme
      - DB_ENV=local
    depends_on:
      - postgres

volumes:
  postgres: